#!/usr/bin/env bash
#transfers a file from our client to a server:

if [ $# -lt 3 ]
then
	echo "Usage: ${0#./} PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
	exit 99
fi


if [ $# -eq 3 ]
then
	file_path=$1
	server_ip=$2
	username=$3
	#key_path=$4

	#Host *
	#StrictHostKeyChecking no
	scp -o StrictHostKeyChecking=no "$file_path" "$username@$server_ip":~/
elif [ $# -eq 4 ]
then
	file_path=$1
        server_ip=$2
        username=$3
        key_path=$4
	scp -o StrictHostKeyChecking=no -i "$key_path" "$file_path" "$username@$server_ip":~/

fi
