#!/usr/bin/env bash
#Install nginx on your server
sudo apt-get -y update
sudo apt-get -y install nginx
#sudo ufw allow 'Nginx HTTP'
sudo sh -c 'echo "Hello World!" > /var/www/html/index.nginx-debian.html'
service nginx start
