#!/usr/bin/env bash
#Install nginx on your server

sudo apt-get -y update
sudo apt-get -y install nginx
sudo ufw allow 'Nginx HTTP'
echo "Hello World!" > /var/www/html/index.nginx-debian.html
echo "Ceci n'est pas une page" > /var/www/html/custom_404.html
echo "server {
	listen 80 default_server;
	listen [::]:80 default_server ipv6only=on;
	

	root /var/www/html;
	index index.html index.htm index.nginx-debian.html;


	server_name _;

	location /redirect_me {
		return 301 https://www.youtube.com/watch?v=QH2-TGUlwu4;
	}

	error_page 404 /custom_404.html;
	location = /custom_404.html {
		root /var/www/html;
		internal;
	}

	location / {
	
	# First attempt to serve request as file, then
	# First attempt to serve request as file, then
	try_files $uri $uri/ =404;

	}

	add_header X-Served-By $(hostname);

	}" > /etc/nginx/sites-enabled/default
sudo service nginx restart

