#!/usr/bin/env bash
#Install load balancer HAproxy

sudo apt-get -y update
sudo apt install -y haproxy
sudo service start haproxy
echo "global
        log /dev/log    local0
        log /dev/log    local1 notice
        chroot /var/lib/haproxy
        stats socket /run/haproxy/admin.sock mode 660 level admin
	stats timeout 30s
	user haproxy
        group haproxy
        daemon

defaults
        log     global
        mode    http
        option  httplog
        option  dontlognull
        contimeout 5000
        clitimeout 50000
        srvtimeout 50000
        errorfile 400 /etc/haproxy/errors/400.http
        errorfile 403 /etc/haproxy/errors/403.http
        errorfile 408 /etc/haproxy/errors/408.http
        errorfile 500 /etc/haproxy/errors/500.http
        errorfile 502 /etc/haproxy/errors/502.http
        errorfile 503 /etc/haproxy/errors/503.http
        errorfile 504 /etc/haproxy/errors/504.http

frontend http
	bind *:80
	mode http

	default_backend web
	
	
backend web
	balance roundrobin
	server web-01 35.153.93.19:80 check
	server web-02 54.172.31.233:80 check" > /etc/haproxy/haproxy.cfg

sudo service restart haproxy
