#!/usr/bin/env bash
#Install load balancer HAproxy

sudo apt-get -y update
sudo apt install -y haproxy
#enable management by an init script
echo "ENABLED=1" >> /etc/default/haproxy
echo "
frontend http
	bind *:80
	mode http
	default_backend web
	
	
backend web
	balance roundrobin
	server web-01 54.197.77.69:80 check
	server web-02 18.233.67.26:80 check" >> /etc/haproxy/haproxy.cfg

sudo systemctl enable haproxy
sudo systemctl restart haproxy
