#!/usr/bin/env bash
#make nginx listen on port 80
sudo apt-get -y update
sudo apt-get -y install nginx
sudo sed -i '26r /dev/stdin' /etc/nginx/sites-available/default <<< "        location /usr/share/nginx/html {
                return 200;
	}"
sudo service nginx start
location /usr/share/nginx/html {
                return 200;
        }

        location / {
