#!/usr/bin/env bash
# This script is displaying "Best School" 10 times
# whith "Hi" at the ninth time
# shellcheck disable=SC2034
str="Best School"
i=0
while [[ $i -lt 10 ]]
do
	echo "$str"
	if [ $i -eq 8 ]
	then
		echo "Hi"
	fi

	(( i += 1 ))
done
