#!/usr/bin/env bash
#displays bad luck for the 4th loop iteration
#displays good luck for the 8th loop iteration
#displays Best School for the other iterations
# shellcheck disable=SC2034
str="Best School"
i=1
while [[ $i -le 10 ]]
do
	if [ $i -eq 4 ]
	then
		echo "bad luck"
	elif [ $i -eq 8 ]
	then
		echo "good luck"
	else
		echo "$str"
	fi

	(( i += 1 ))
done
