#!/usr/bin/env bash
#displays 4 and then bad luck from China for the 4th loop iteration
#displays 9 and then bad luck from Japan for the 9th loop iteration
#displays 17 and then bad luck from Italy for the 17th loop iteration
# shellcheck disable=SC2034
str="Best School"
i=1
while [[ $i -le 20 ]]
do
	echo "$i"

	case "$i" in
		#case 1
		"4") echo "bad luck from China";;
		#case 2
		"9") echo "bad luck from Japan";;
		#case 3
		"17") echo "bad luck from Italy";;
	esac
	(( i += 1 ))
done
