#!/usr/bin/env bash
#display hours from 0 to 12
#display minutes from 1 to 59
# shellcheck disable=SC2034
str="Best School"
i=0
while [[ $i -le 12 ]]
do
	echo "Hour: $i"
	j=1
	while [[ $j -le 59 ]]
	do
		echo "$j"
		(( j += 1 ))
	done
	(( i += 1 ))
done
